# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1141f885ebd94fd2d9d344182cab47ca06cd41ee9b0b6ec7f9b2ee767bbaa7fb9e56a5efbe1a518c3f9a37bf0f704a641219c7f1dfa457c953d68460624b2210

test:
  secret_key_base: 35be1d71a06d7ffd8fa26d6484c9506be6d91d9869666273e49c3330a2043064c595106ada2f2bb4e2831ada1c1ef3fc5a1350cd16c8e45e4a7f5f5e38fea6b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
